#!/bin/bash
cd "$(git rev-parse --show-toplevel)"
ESLINT="node_modules/.bin/eslint"
CLIENT_ESLINT="./client/node_modules/.bin/eslint"
pwd

if [[ ! -x "$ESLINT" ]]; then
  printf "\t\033[41mPlease install ESlint\033[0m (npm install eslint)\n"
  exit 1
fi

SERVER_FILES=($(git diff --cached --name-only --diff-filter=ACM ./server | grep ".jsx\{0,1\}$"))
CLIENT_FILES=($(git diff --cached --name-only --diff-filter=ACM ./client | grep -E "(.css)|(.scss)|(.vue)|(.jsx{0,1})"))

echo "ESLint'ing ${#SERVER_FILES[@]} files"

if [[ "$SERVER_FILES" != "" ]]; then

	$ESLINT "${SERVER_FILES[@]}" --fix
	ESLINT_EXIT="$?"

# Re-add files since they may have been fixed
	git add "${SERVER_FILES[@]}"

	if [[ "${ESLINT_EXIT}" == 0 ]]; then
		printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
	else
		printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
		exit 1
	fi

fi

echo "ESLint'ing ${#CLIENT_FILES[@]} files"

if [[ "$CLIENT_FILES" = "" ]]; then
  exit 0
fi

$CLIENT_ESLINT --resolve-plugins-relative-to "client/" "${CLIENT_FILES[@]}" --fix
CLIENT_ESLINT_EXIT="$?"

# Re-add files since they may have been fixed
git add "${CLIENT_FILES[@]}"
if [[ "${CLIENT_ESLINT_EXIT}" == 0 ]]; then
  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
else
  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
  exit 1
fi

exit $?
